---
#
# Ansible playbook to Install iOS Simulators
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  become_method: sudo
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  roles:
    - install-simulators
