---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  tasks:
    #
    # Required param checks
    - fail: msg="bitrise_box_version not defined (format example 'r2p3')"
      when: bitrise_box_version|default("") == ""
    - debug: msg=" (i) bitrise_box_version = {{ bitrise_box_version }}"

    #
    # Setup the debug log file for custom scripts
    #  [!] Collect custom script outputs to ~/Desktop/debug.log on the remote host!
    # You can inspect it during setup with $ tail -f ~/Desktop/debug.log
    #  custom installer scripts (the ones in ./installers folder) use this debug log file
    - file: path=/Users/{{ param_user }}/Desktop/debug.log
        state=touch
        owner="{{ param_user }}"
        mode=0644

    #
    # Add user to sudoers-no-password
    - name: "Add user {{ param_user }} to sudoers with no password"
      sudo: yes
      lineinfile: "dest=/etc/sudoers
        regexp='^{{ param_user }} ALL'
        line='{{ param_user }} ALL=(ALL) NOPASSWD: ALL'
        state=present
        validate='visudo -cf %s'"

    #
    # SSH config
    - name: ensure .ssh folder is ok
      file: path=/Users/{{ param_user }}/.ssh
        state=directory
        owner="{{ param_user }}"
        mode=0700
    - name: copy ssh key to remote's {{ param_user }} user
      copy: src=setupfiles/authorized_keys
        dest="/Users/{{ param_user }}/.ssh/authorized_keys"
        owner="{{ param_user }}"
        mode=0600
    - name: sshd_config settings
      sudo: yes
      lineinfile: dest=/etc/sshd_config
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state="{{ item.state }}"
      with_items:
        # PasswordAuthentication no
        - { regexp: '^PasswordAuthentication yes', line: '', state: "absent" }
        - { regexp: '^PasswordAuthentication no', line: 'PasswordAuthentication no', state: "present" }
        # PermitEmptyPasswords no
        - { regexp: '^PermitEmptyPasswords yes', line: '', state: "absent" }
        - { regexp: '^PermitEmptyPasswords no', line: 'PermitEmptyPasswords no', state: "present" }
        # # LoginGraceTime 1m
        - { regexp: '^LoginGraceTime', line: 'LoginGraceTime 1m', state: "present" }
        # PermitRootLogin no
        - { regexp: '^PermitRootLogin yes', line: '', state: "absent" }
        - { regexp: '^PermitRootLogin no', line: 'PermitRootLogin no', state: "present" }
        # # LogLevel 1m
        - { regexp: '^LogLevel', line: 'LogLevel VERBOSE', state: "present" }
        # UsePAM no -> if this is not set to 'no' then password authentication still possible!
        - { regexp: '^UsePAM yes', line: '', state: "absent" }
        - { regexp: '^UsePAM no', line: 'UsePAM no', state: "present" }
        # ChallengeResponseAuthentication
        - { regexp: '^ChallengeResponseAuthentication yes', line: '', state: "absent" }
        - { regexp: '^ChallengeResponseAuthentication no', line: 'ChallengeResponseAuthentication no', state: "present" }
        # UseDNS no -> for better speed
        - { regexp: '^UseDNS yes', line: '', state: "absent" }
        - { regexp: '^UseDNS no', line: 'UseDNS no', state: "present" }

    #
    # Setup profiles
    - name: setup .bitrise_profile
      copy: src=profiles/bitrise_profile
        dest="/Users/{{ param_user }}/.bitrise_profile"
        owner="{{ param_user }}"
        mode=0600
    - name: setup .bashrc
      copy: src=profiles/bashrc
        dest="/Users/{{ param_user }}/.bashrc"
        owner="{{ param_user }}"
        mode=0600
    - name: setup .profile
      copy: src=profiles/profile
        dest="/Users/{{ param_user }}/.profile"
        owner="{{ param_user }}"
        mode=0600
    - name: setup .bash_profile
      copy: src=profiles/bash_profile
        dest="/Users/{{ param_user }}/.bash_profile"
        owner="{{ param_user }}"
        mode=0600

    #
    # Install and update homebrew
    - name: run brew installer script
      script: installers/install_brew.sh creates=/usr/local/bin/brew
    - homebrew: update_homebrew=yes upgrade_all=yes
    - name: check brew doctor
      shell: brew doctor
    # brew some commands
    - homebrew: name=git state=latest
    - homebrew: name=wget state=latest
    - homebrew: name=mercurial state=latest
    - homebrew: name=xctool state=latest
    - homebrew: name=node state=latest
    ## Go
    # Gopath is $HOME/go
    - homebrew: name=go state=latest
    - file: path="/Users/{{ param_user }}/go/{{ item.fold_path }}"
        state=directory
        owner="{{ param_user }}"
      with_items:
        - { fold_path: 'src' }
        - { fold_path: 'bin' }
        - { fold_path: 'pkg' }

    #
    # Install and setup RVM with Ruby
    - name: run RVM installer script
      script: installers/install_rvm.sh creates=/Users/{{ param_user }}/.rvm/bin/rvm
    - command: rvm install ruby-2.1.3
    - command: rvm install ruby-2.1.2
    - shell: bash --login -c "rvm use 2.1.3 --default"
    - command: rvm osx-ssl-certs update all
    - shell: sudo gem update --system
    - shell: bash --login -c "gem update"
    # GEMs: Cocoapods
    - shell: bash --login -c "gem install cocoapods"
    - shell: bash --login -c "pod setup"

    #
    # Setup Bitrise specific folders
    #
    # Setup base logs and pids folders
    - file: path="/Users/{{ param_user }}/{{ item.fold_path }}"
        state=directory
        owner="{{ param_user }}"
      with_items:
        # BITRISE_SOURCE_DIR
        - { fold_path: 'git' }
        # BITRISE_STEP_DIR
        - { fold_path: 'stepdir' }
        # BITRISE_DEPLOY_DIR
        - { fold_path: 'deploy' }
        # BITRISE_LIBRARY_DIR
        - { fold_path: 'Library/MobileDevice/Provisioning Profiles' }
        # BITRISE_PROFILE_DIR
        - { fold_path: 'profiles' }
        # BITRISE_SYM_ROOT
        - { fold_path: 'build' }
        # BITRISE_OBJ_ROOT
        - { fold_path: 'bin' }
        # BITRISE_FOLDER_PATH
        - { fold_path: 'bitrise' }
        # BITRISE_STEP_DATA_FOLDER_PATH
        - { fold_path: 'bitrise/stepdata' }
    #
    # Install XCUServer
    - name: run XCUServer installer script
      script: installers/install_xcuserver.sh creates=/Users/{{ param_user }}/Library/LaunchAgents/bitrise.tools.osx.xcuserver.plist

    - name: setup Desktop/box-info.json
      template: src=setupfiles/box-info.json.template
        dest="/Users/{{ param_user }}/Desktop/box-info.json"
        owner="{{ param_user }}"
        mode=0600

    #
    # Prepare
    ## Bootstrap script
    - name: setup .bootstrap.sh
      copy: src=setupfiles/bootstrap.sh
        dest="/Users/{{ param_user }}/.bootstrap.sh"
        owner="{{ param_user }}"
        mode=0700
    ## step_agent
    - name: setup .step_agent
      copy: src=step-agent/bin/step_agent_osx
        dest="/Users/{{ param_user }}/.step_agent"
        owner="{{ param_user }}"
        mode=0700
    ## git_clone script and ssh no-prompt script
    - name: setup ssh_no_prompt.sh
      copy: src=steps-git-clone/ssh_no_prompt.sh
        dest="/Users/{{ param_user }}/ssh_no_prompt.sh"
        owner="{{ param_user }}"
        mode=0700
    - name: setup git_clone.rb
      copy: src=steps-git-clone/git_clone.rb
        dest="/Users/{{ param_user }}/git_clone.rb"
        owner="{{ param_user }}"
        mode=0700

    #
    # Final debug prints
    - debug: msg="---> Finished with automatic stuff - but here's some things you have to do manually:"
    - debug: msg=" (!) After you finished with the preparations RESTART the machine!"
    - debug: msg="---> Finished"
