---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  become_method: sudo
  any_errors_fatal: True
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  tasks:
    # ----------------------------------------
    # --- pre-installed tool cache updates ---
    # ----------------------------------------

    - name: "brew update"
      shell: bash -l -c "brew update"

    - name: "CocoaPods: pod setup"
      shell: bash -l -c "pod setup"


    # ----------------------------------------
    # --- Bitrise CLI tools ---
    # ----------------------------------------
    - name: "bitrise CLI: cleanup previous tool versions"
      shell: bash -l -c "rm /usr/local/bin/bitrise /usr/local/bin/stepman /usr/local/bin/envman"
    - name: "bitrise CLI: download"
      shell: bash -l -c "curl -fL https://github.com/bitrise-io/bitrise/releases/download/1.3.1/bitrise-$(uname -s)-$(uname -m) > /usr/local/bin/bitrise"
    - name: "Make the bitrise CLI executable"
      file: path=/usr/local/bin/bitrise mode="u=rwx,g=rx,o=rx"
    - name: "Bitrise CLI test -version"
      shell: bash -l -c "bitrise --version"
    - name: "Bitrise CLI - setup -minimal"
      shell: bash -l -c "bitrise setup --minimal"
    # setup the default StepLib collection to stepman, for a pre-warmed
    #  cache for the StepLib
    - name: "stepman: init"
      shell: bash -l -c "stepman setup -c https://github.com/bitrise-io/bitrise-steplib.git"
    - name: "stepman: update"
      shell: bash -l -c "stepman update"


    # ----------------------------------------
    # --- Cleanup ---
    # ----------------------------------------

    # Remove tmp / test dirs inside the HOME directory
    #  * DerivedData : remove the DerivedData content generated by the Bitrise Stack tester sample apps (built during Stack prepare, to validate the Xcode setup)
    - file: path="/Users/{{ param_user }}/{{ item.fold_path }}"
        state=absent
      with_items:
        - { fold_path: 'Library/Developer/Xcode/DerivedData' }

    # ------------------------
    # --- shut down the VM ---
    # ------------------------
    - name: Shut down
      shell: sleep 2 && sudo shutdown -h now "Caches updated"
      async: 1
      poll: 0
      ignore_errors: true
