---
- name: Install gem packages
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "$HOME/.rbenv/shims/gem"
    user_install: false
  with_items:
    - "{{ gem_packages }}"

# GEMs: Cocoapods
- name: pod setup
  shell: bash -l -c "pod setup"
  retries: 3
  when: is_incremental_setup|default(false) == false

- name: "CocoaPods: pod repo update"
  shell: bash -l -c "pod repo update"
