---
- name: Install xcode-install
  gem:
    name: xcode-install
    user_install: false
    executable: "$HOME/.rbenv/shims/gem"

- name: Install xcode version based on xcode_version variable, it could take a while. About an hour, so be patient.
  shell: bash -l -c "xcversion install '{{ xcode_version }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"

- name: Enable accessibility to xcode
  script: enable_accessibility.sh
  become: true
