---
- name: load simulator versions
  include_vars: "{{ XCODE_VERSION }}.yml"

- name: Install simulators
  include: install.yml
  with_items:
    - "{{ simulators }}"
  loop_control:
    loop_var: item

- name: Cleanup cached downloads
  shell: bash -l -c "xcversion cleanup"
  become: true
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
